// update transactions
const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';

// edit transactions
const EDIT_SELECTED = 'EDIT_SELECTED';
const UPDATE_SELECTED = 'UPDATE_SELECTED';
const CANCEL_EDITING = 'CANCEL_EDITING';

// displaying footer
const SHOW_FOOTER = 'SHOW_FOOTER';
const HIDE_FOOTER = 'HIDE_FOOTER';

// summary
const UPDATE_WEEK_EXPENSES = 'UPDATE_WEEK_EXPENSES';
const UPDATE_MONTH_EXPENSES = 'UPDATE_MONTH_EXPENSES';
const UPDATE_MONTH_INCOME = 'UPDATE_MONTH_INCOME';

// loading
const LOADING = 'LOADING';
const FINISHED_LOADING = 'FINISHED_LOADING';

// error
const ERROR = 'ERROR';

export {
  UPDATE_TRANSACTIONS,
  EDIT_SELECTED,
  UPDATE_SELECTED,
  CANCEL_EDITING,
  SHOW_FOOTER,
  HIDE_FOOTER,
  UPDATE_WEEK_EXPENSES,
  UPDATE_MONTH_EXPENSES,
  UPDATE_MONTH_INCOME,
  LOADING,
  FINISHED_LOADING,
  ERROR
}